name: Build {{ cookiecutter.project_slug }} Package

on: [push]

jobs:
  build:
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: {% raw %}${{ matrix.python }}{% endraw %}

      - name: Build {{ cookiecutter.project_slug }}
        run: python setup.py clean --all install
