name: Run Tests

on: [push]

jobs:
  build-ubuntu-mac:
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '20.1.0.java11'
    - run: java -version
    - run: gu install native-image
    - name: Run gradle tests
      run: ./gradlew test

  build-windows:
    runs-on: {% raw %}${{ matrix.os }}{% endraw %}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/setup-graalvm@2.0
        with:
          graalvm-version: '19.3.0.2.java11'
      - run: java -version
      - name: Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools
        run: |
          choco install visualstudio2017-workload-vctools
      - name: set env variables and run the Gradle build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          ./gradlew test
