version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    target_branch: "development"
    update_schedule: "daily"
    default_labels:
        - "dependabot"
    commit_message:
        prefix: "[DEPENDABOT]"