name: Check version upgrade

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: Clone me
          run: git clone https://github.com/Imipenem/MyTestRepo

        - name: Install cookietemple
          run: pip install MyTestRepo/

        - uses: actions/checkout@v2
          name: Check out source-code repository

        - name: Check for new template version
          run: if cookietemple sync --check_update | grep -q 'cookietemple sync';then echo "New template version is available. Use cookietemple sync to update."; exit 1;else echo "No update found";exit 0;fi
