name: PR to master only from Development

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR branch to master is development
        run: |
            echo "Pull request's branch to be merged is: ${{ github.event.pull_request.head.ref }}"
            if [ "${{ github.event.pull_request.head.ref }}" != "development" ]; then echo "PRs only from development branch to master"; exit 1; fi

