name: Create pub-thesis-template Template

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Build thesis
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
