name: Run unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11, 12, 13, 14 ]
    name: Java ${{ matrix.java }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      # Disabled until Github Actions finds a way to allow GUIs to run
      # Our GUI unit tests would result in errors
      #- name: Run tests
      #  run: mvn clean verify
