version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "development"
    default_labels:
      - "dependabot"
    commit_message:
      prefix: "[DEPENDABOT]"
