name: Run Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python: [3.7, 3.8]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}

    - name: Generate coverage report
      run: |
        pip install -r requirements_dev.txt
        pip install pytest-cov
        pytest --cov-config=.coveragerc --cov=./tests --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
