name: Create pub-thesis-template Template

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Build Cookietemple
        run: |
          python setup.py clean --all install

      - name: Create pub-thesis-latex Template
        run: |
          echo -e "pub\nthesis\nHomer\nExplodingSpringfield\nTitle\nSpringfieldUniversity\nNuclearDepartment\nhomergithub\nPhD\nn" | cookietemple create

      - name: Build thesis
        uses: xu-cheng/latex-action@master
        with:
          root_file: thesis.tex
          working_directory: ExplodingSpringfield
