name: Create cli-python Template

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Build Cookietemple
        run: |
          python setup.py clean --all install

      - name: Create cli-python Template
        run: |
          echo -e "cli\npython\nHomer\nhomer.simpson@hotmail.com\nExplodingSpringfield\ndescription\n1.0.0\nMIT\nClick\npytest\nn" | cookietemple create



