name: Create gui-java Template

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
        name: Check out source-code repository

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Build Cookietemple
        run: |
          python setup.py clean --all install

      - name: Create gui-java Template
        run: |
          echo -e "gui\njava\nHomer\nhomer.simpson@hotmail.com\nExplodingSpringfield\ndescription\n1.0.0\nMIT\nhomergithub\nburnsorga\nn" | cookietemple create

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile Package
        run: |
             cd ExplodingSpringfield
             make compile
    name: Create cli-python Template

    on: [push]

    jobs:
        build:

            runs-on: ubuntu-latest
            strategy:
                matrix:
                    python: [3.7, 3.8]

            steps:
                - uses: actions/checkout@v2
                  name: Check out source-code repository

                - name: Setup Python
                  uses: actions/setup-python@v1
                  with:
                      python-version: ${{ matrix.python }}

                - name: Build Cookietemple
                  run: |
                      python setup.py clean --all install

                - name: Create cli-python Template
                  run: |
                      echo -e "cli\npython\nHomer\nhomer.simpson@hotmail.com\nExplodingSpringfield\ndescription\n1.0.0\nMIT\nhomergithub\nClick\npytest\nn" | cookietemple create

                - name: Build Package
                  run: |
                      cd ExplodingSpringfield
                      make install

                - name: Install pip
                  run: |
                      python -m pip install --upgrade pip

                - name: Install doc dependencies
                  run: |
                      pip install -r docs/requirements.txt

                - name: Build docs
                  run: |
                      cd docs
                      make html

